source ~/.zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
# antigen bundle heroku
# antigen bundle pip
# antigen bundle lein
# antigen bundle command-not-found

# Additional plugins
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# Tell Antigen that you're done.
antigen apply

source ~/.aliases

# Pure prompt theme
fpath+=($HOME/.zsh/pure)
zstyle :prompt:pure:git:branch color green
autoload -U promptinit; promptinit
prompt pure
bindkey '^E' end-of-line
